name: "foundry-gas-report"
description: "Generates a report about differences between two JSON files."
inputs:
  heading: 
    description: "The heading to use for the report."
    required: false
    default: "Gas report"
  token:
    description: "The GitHub token to use for the API requests."
    required: true
  files:
    description: "The files that should be compared. A glob is accepted."
    required: false
    default: |
      snapshots/*.json

outputs:
  report:
    description: "The report"

runs:
  using: "node20"
  main: dist/action.js
