name: "foundry-gas-report"
description: "Generates a report about differences between versions of JSON files in a pull request."
inputs:
  heading: 
    description: "The heading to use for the report."
    required: false
    default: "Forge Gas Snapshots"
  token:
    description: "The GitHub token to use for the API requests."
    required: false
    default: ${{ github.token }}
  files:
    description: "The files that should be compared. A glob is accepted."
    required: false
    default: |
      snapshots/*.json
  base_ref:
    description: "The ref to compare against. Uses the base ref of the pull request if not provided."
    required: false

outputs:
  report:
    description: "The report"

runs:
  using: "node20"
  main: dist/action.js
