# creates a new npm release
name: test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@v4.2.2
      - name: test action
        id: gas
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          heading: "Gas report"
          baseBranch: "main"
          files: |
            mocks/*.json

      - name: Prepare comment
        run: |
          printf '%s' "${{ steps.gas.outputs.report }}<!-- gas-report -->" > /tmp/template.md

      - name: Find Comment
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: <!-- gas-report -->

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body-path: /tmp/template.md
          edit-mode: replace
