# creates a new npm release
name: test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@v4.2.2

      - uses: bgd-labs/github-workflows/.github/actions/setup-node@main

      - name: test lib
        run: npm test -- --run

      - name: test action
        uses: ./
        with:
          ROOT_REPORT_PATH: "mocks/gas.backup.json"
          REPORT_PATH: "mocks/gas.json"
